services:
  ownbook:
    labels:
      uzqw.observe: 'true'
      uzqw.app: ownbook
    networks:
      - cicd-observability

networks:
  cicd-observability:
    external: true
    name: cicd-observability
